cursor #8ecff2
cursor_text_color #8ecff2

foreground            #dfe3e7
background            #001e2b
selection_foreground  #20333d
selection_background  #b5c9d7
url_color             #8ecff2

# black
color0  #343F44
color8  #5C6A72

# red
color1  #ffb4ab
color9  #F85552

# green
color2  #A7C080
color10 #8DA101

# yellow
color3  #DBBC7F
color11 #DFA000

# blue
color4  #8ecff2
color12 #3A94C5

# magenta
color5  #D699B6
color13 #DF69BA

# cyan
color6  #83C092
color14 #35A77C

# white
color7  #e7e7e7
color15 #DFDDC8
