# Blood
# Theme create by: https://github.com/charlesrocket
# Update by(sort by time):

# Thank you!

code_syntax_highlight = "matugen"

# border
file_panel_border = "#8a9297"
sidebar_border = "#8a9297"
footer_border = "#8a9297"

# border active
file_panel_border_active = "#c0e8ff"
sidebar_border_active = "#c0e8ff"
footer_border_active = "#e4dfff"
modal_border_active = "#c0e8ff"

# background (bg)
full_screen_bg = "#001e2b"
file_panel_bg = "#001e2b"
sidebar_bg = "#001e2b"
footer_bg = "#302d4c"
modal_bg = "#003547"

# foreground (fg)
full_screen_fg = "#8dcff1"
file_panel_fg = "#8dcff1"
sidebar_fg = "#8dcff1"
footer_fg = "#c8c2ea"
modal_fg = "#8dcff1"

# special color
cursor = "#c0e8ff"
correct = "#c0e8ff"
error = "#ffb4ab"
hint = "#dfe3e7"
cancel = "#ffb4ab"
gradient_color = ["#8dcff1", "#c8c2ea"]

# file panel special items
file_panel_top_directory_icon = "#b4cad6"   #"#c0c7cd"
file_panel_top_path = "#b4cad6"
file_panel_item_selected_fg = "#1f333d"
file_panel_item_selected_bg = "#b4cad6"

# sidebar special items
sidebar_title = "#dfe3e7"
sidebar_item_selected_fg = "#003547"
sidebar_item_selected_bg = "#8dcff1"
sidebar_divider = "#b4cad6"

# modal special items
modal_cancel_fg = "#ffb4ab"
modal_cancel_bg = "#690005"

modal_confirm_fg = "#dfe3e7"
modal_confirm_bg = "#0f1417"

# help menu
help_menu_hotkey = "#dfe3e7"
help_menu_title = "#c0c7cd"
