# Blood
# Theme create by: https://github.com/charlesrocket
# Update by(sort by time):

# Thank you!

code_syntax_highlight = "matugen"

# border
file_panel_border = "#8a938b"
sidebar_border = "#8a938b"
footer_border = "#8a938b"

# border active
file_panel_border_active = "#b0f1c3"
sidebar_border_active = "#b0f1c3"
footer_border_active = "#beeaf7"
modal_border_active = "#b0f1c3"

# background (bg)
full_screen_bg = "#00210f"
file_panel_bg = "#00210f"
sidebar_bg = "#00210f"
footer_bg = "#023640"
modal_bg = "#00391e"

# foreground (fg)
full_screen_fg = "#94d5a8"
file_panel_fg = "#94d5a8"
sidebar_fg = "#94d5a8"
footer_fg = "#a3cddb"
modal_fg = "#94d5a8"

# special color
cursor = "#b0f1c3"
correct = "#b0f1c3"
error = "#ffb4ab"
hint = "#dfe4dd"
cancel = "#ffb4ab"
gradient_color = ["#94d5a8", "#a3cddb"]

# file panel special items
file_panel_top_directory_icon = "#b6ccb9"   #"#c0c9c0"
file_panel_top_path = "#b6ccb9"
file_panel_item_selected_fg = "#213527"
file_panel_item_selected_bg = "#b6ccb9"

# sidebar special items
sidebar_title = "#dfe4dd"
sidebar_item_selected_fg = "#00391e"
sidebar_item_selected_bg = "#94d5a8"
sidebar_divider = "#b6ccb9"

# modal special items
modal_cancel_fg = "#ffb4ab"
modal_cancel_bg = "#690005"

modal_confirm_fg = "#dfe4dd"
modal_confirm_bg = "#0f1511"

# help menu
help_menu_hotkey = "#dfe4dd"
help_menu_title = "#c0c9c0"
