[colors]
accent = '#BDA99EFF'
background = '#18423FFF'
base00 = '#18423FFF'
base01 = '#447571FF'
base02 = '#9A8652FF'
base03 = '#B47837FF'
base04 = '#9A5552FF'
base05 = '#AA477BFF'
base06 = '#3A898CFF'
base07 = '#D3734AFF'
base08 = '#A4341AFF'
base09 = '#A9DC86FF'
base0A = '#B6AB82FF'
base0B = '#C5916BFF'
base0C = '#AC7676FF'
base0D = '#B0779EFF'
base0E = '#849899FF'
base0F = '#C6C6C6FF'
border = '#242424FF'
border_focused = '#2E2E2EFF'
cursor = '#D2D2D2FF'
editor_background = '#18423FFF'
editor_command = '#3A898CFF'
editor_comment = '#849899FF'
editor_disabled = '#849899FF'
editor_emphasis = '#A9DC86FF'
editor_error = '#A4341AFF'
editor_inactive = '#849899FF'
editor_line_number = '#849899FF'
editor_link = '#B0779EFF'
editor_main = '#D3734AFF'
editor_selected = '#242424FF'
editor_selection_inactive = '#1D1C1CFF'
editor_string = '#9A8652FF'
editor_success = '#668A51FF'
editor_warning = '#B47837FF'
error = '#A4341AFF'
foreground = '#9CACA4FF'
info = '#3A898CFF'
on_background = '#9CACA4FF'
on_error = '#D2D2D2FF'
on_info = '#D2D2D2FF'
on_success = '#D2D2D2FF'
on_surface = '#D3734AFF'
on_surface_variant = '#D4D4D4FF'
on_warning = '#D2D2D2FF'
success = '#68948AFF'
surface = '#170E0BFF'
surface_variant = '#191919FF'
warning = '#B47837FF'

[general]
name = 'lofi-girl-010'