# More option see https://github.com/DreamMaoMao/mango/wiki/

# sub config load
source=./env.conf
source=./animation.conf
source=./input.conf
source=./layout.conf
source=./theme.conf
source=./bind.conf
source=./rule.conf
source=./color.conf

# run autostart
exec-once=~/.config/mango/autostart.sh
